# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eEQXuhZVAg1D3ydtXepcXAxREuq-gOq
"""

!pip install streamlit

!pip install pyngrok

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

!unzip ngrok-stable-linux-amd64.zip

!ngrok authtoken 1ydVNd4hvD5P2DyPz8ZZb41lUyz_7KXhzuVYn2biRfwEzUH18

from pyngrok import ngrok

!pip install folium
!pip install streamlit_folium

#import streamlit as st
!pip install pandas
#import pandas as pd
!pip install numpy
#import numpy as np
!pip install altair
#import altair as alt
!pip install pydeck
#import pydeck as pdk

!killall ngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile mysl.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import folium as fo
# from streamlit_folium import folium_static
# import geopandas as gp
# 
# st.title('Streamlit with Folium')
# 
# """
# ## An easy way to create a website using Python
# """
# 
# df = pd.read_csv('https://raw.githubusercontent.com/Maplub/MonthlyAirQuality/master/sensorlist.csv')
# 
# tambol = st.text_input(label='ตำบล')
# 
# st.write(df[df['tambol'] == tambol])
# 
# 
# crs = "EPSG:4326"
# geometry = gp.points_from_xy(df.lon,df.lat)
# geo_df  = gp.GeoDataFrame(df,crs=crs,geometry=geometry)
# 
# nan_boundary  = gp.read_file('https://github.com/Maplub/AirQualityData/blob/master/nan_shp_wgs84.zip?raw=true')
# nanall = nan_boundary.unary_union
# 
# nan_sta = geo_df.loc[geo_df.geometry.within(nanall)]
# 
# 
# longitude = 100.819200
# latitude = 19.331900
# 
# station_map = fo.Map(
# 	location = [latitude, longitude], 
# 	zoom_start = 10)
# 
# latitudes = list(nan_sta.lat)
# longitudes = list(nan_sta.lon)
# labels = list(nan_sta.name)
# 
# for lat, lng, label in zip(latitudes, longitudes, labels):
# 	fo.Marker(
# 		location = [lat, lng], 
# 		popup = label,
# 		icon = fo.Icon(color='red', icon='heart')
# 	).add_to(station_map)
# 
# folium_static(station_map)

!streamlit run --server.port 80 app.py&>/dev/null&

publ_url = ngrok.connect(port='80')

publ_url

!pgrep streamlit

# Important library for many geopython libraries
!apt install gdal-bin python-gdal python3-gdal 
# Install rtree - Geopandas requirement
!apt install python3-rtree 
# Install Geopandas
!pip install git+git://github.com/geopandas/geopandas.git
# Install descartes - Geopandas requirement
!pip install descartes 
# Install Folium for Geographic data visualization
!pip install folium
# Install plotlyExpress
!pip install plotly_express

